pipelines:
  pipeline-a1:
    group: group-a
    materials:
      gocd-config-test:
        git: https://github.com/michaelbannister/gocd-config-test.git
    stages:
      - defaultStage:
          clean_workspace: true
          jobs:
            defaultJob:
              tasks:
                - exec:
                    command: /bin/sh
                    arguments: [ "-c", 'echo "$GO_PIPELINE_NAME $GO_PIPELINE_COUNTER" > output.txt' ]
              artifacts:
                - build: { source: "output.txt" }
  pipeline-a2:
    group: group-a
    materials:
      upstream:
        pipeline: defaultPipeline
        stage: defaultStage
    stages:
      - defaultStage:
          jobs:
            defaultJob:
              tasks:
                - fetch:
                    pipeline: pipeline-a1
                    stage: defaultStage
                    job: defaultJob
                    source: output.txt
                    is_file: yes
                    destination: inputs
  pipeline-a3:
    group: group-a
    materials:
      gocd-config-test:
        git: https://github.com/michaelbannister/gocd-config-test.git
    stages:
      - defaultStage:
          approval:
            type: manual
          tasks:
            - exec:
                command: whoami
  pipeline-b1:
    group: group-b
    materials:
      gocd-config-test:
        git: https://github.com/michaelbannister/gocd-config-test.git
    stages:
      - defaultStage:
          approval:
            type: manual
          tasks:
            - exec:
                command: whoami
  pipeline-b2:
    group: group-b
    materials:
      gocd-config-test:
        git: https://github.com/michaelbannister/gocd-config-test.git
    stages:
      - defaultStage:
          approval:
            type: manual
          tasks:
            - exec:
                command: whoami
  pipeline-b3:
    group: group-b
    materials:
      gocd-config-test:
        git: https://github.com/michaelbannister/gocd-config-test.git
    stages:
      - defaultStage:
          approval:
            type: manual
          tasks:
            - exec:
                command: whoami
